name: Job-Seeker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USER }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGO_DATABASE }}
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"  
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    
    - name: Install MongoDB client
      run: sudo apt-get update && sudo apt-get install -y mongodb-clients

    - name: Wait for MongoDB to be read
      env:
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017
      run: |
        for i in {1..30}; do
          if mongo --host mongo --eval 'db.runCommand({ ping: 1 })'; then
            echo "MongoDB is up and running!"
            break
          fi
          echo "Waiting for MongoDB to start..."
          sleep 2
        done

    - name: Build with Maven
      run: mvn -B package --file server/pom.xml

    - name: Run tests
      env:
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017
      run: mvn test --file server/pom.xml

    - name: Build Docker image
      run: docker build -t job-seeker .

    - name: Run application
      env:
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_URI: mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017
        SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
      run: docker-compose up --build -d

    - name: Access application
      run: curl http://localhost:3000

    - name: Cleanup
      run: docker-compose down
